
import type { Patient, Appointment } from './types';
import { format, subDays, addDays } from 'date-fns';

const today = new Date();

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'patient-1',
    nephroId: '1001/0824',
    name: 'Aarav Sharma',
    dob: '1968-05-15',
    gender: 'Male',
    contact: '9876543210',
    email: 'aarav.sharma@example.com',
    address: { street: '123 MG Road', city: 'Pune', state: 'Maharashtra', pincode: '411001' },
    guardian: { name: 'Priya Sharma', relation: 'Spouse', contact: '9876543211' },
    registrationDate: subDays(today, 90).toISOString(),
    createdAt: subDays(today, 90).toISOString(),
    patientStatus: 'OPD',
    isTracked: true,
    residenceType: 'Urban',
    nextAppointmentDate: addDays(today, 14).toISOString(),
    clinicalProfile: {
      primaryDiagnosis: 'Diabetic Nephropathy',
      tags: ['Diabetes', 'CKD Stage 3', 'Hypertension', 'PD'],
      nutritionalStatus: 'Well-nourished',
      disability: 'None',
      subspecialityFollowUp: 'Endocrinology',
      smokingStatus: 'No',
      alcoholConsumption: 'No',
      vaccinations: [
        { name: 'Hepatitis B', administered: true, date: '2023-01-10', nextDoseDate: '2023-02-10' },
        { name: 'Pneumococcal', administered: true, date: '2023-03-15', nextDoseDate: null },
        { name: 'Influenza', administered: false, date: null, nextDoseDate: null },
        { name: 'Covid', administered: true, date: '2022-11-20', nextDoseDate: null },
        { name: 'Varicella', administered: false, date: null, nextDoseDate: null },
      ],
      pomr: "Long-standing T2DM with progressive proteinuria. Now CKD G3bA3. On ARB and SGLT2i.",
      aabhaNumber: 'ABHA-111',
      bloodGroup: 'O+',
      drugAllergies: 'Sulfa drugs',
      whatsappNumber: '9876543210',
      hasDiabetes: true,
      onAntiHypertensiveMedication: true,
      onLipidLoweringMedication: true,
    },
    visits: [
        {
            id: 'visit-1-1',
            date: subDays(today, 80).toISOString(),
            createdAt: subDays(today, 80).toISOString(),
            visitType: 'Routine',
            visitRemark: 'Initial consultation after referral.',
            groupName: 'Diabetic Nephropathy',
            patientId: 'patient-1',
            diagnoses: [{id: 'diag-1', name: 'Diabetic Nephropathy', icdCode: 'E11.21' }],
            clinicalData: {
                history: 'Patient referred from primary care for persistent proteinuria.',
                height: '175', weight: '78', bmi: '25.47', idealBodyWeight: '68.27',
                pulse: '76', systolicBP: '145', diastolicBP: '88', respiratoryRate: '16',
                generalExamination: 'Mild pedal edema noted.',
                medications: [
                    { id: 'med-1', name: 'Telmisartan', dosage: '40mg', frequency: 'OD' },
                    { id: 'med-2', name: 'Metformin', dosage: '500mg', frequency: 'BD' }
                ]
            }
        },
        {
            id: 'visit-1-2',
            date: subDays(today, 30).toISOString(),
            createdAt: subDays(today, 30).toISOString(),
            visitType: 'Follow-up',
            visitRemark: 'Added SGLT2 inhibitor.',
            groupName: 'Diabetic Nephropathy',
            patientId: 'patient-1',
            diagnoses: [{id: 'diag-1', name: 'Diabetic Nephropathy', icdCode: 'E11.21' }],
            clinicalData: {
                history: 'Follow-up to assess response to ARB. Proteinuria persists.',
                systolicBP: '138', diastolicBP: '82',
                medications: [
                    { id: 'med-1', name: 'Telmisartan', dosage: '40mg', frequency: 'OD' },
                    { id: 'med-3', name: 'Dapagliflozin', dosage: '10mg', frequency: 'OD' },
                    { id: 'med-2', name: 'Metformin', dosage: '500mg', frequency: 'BD' }
                ]
            }
        }
    ],
    investigationRecords: [
      { id: 'inv-1-1', date: subDays(today, 80).toISOString(), tests: [
          { id: 'test-1', group: 'Biochemistry', name: 'Serum Creatinine', result: '1.5', unit: 'mg/dL', normalRange: '0.6-1.2' },
          { id: 'test-2', group: 'Biochemistry', name: 'eGFR', result: '55', unit: 'mL/min/1.73m²', normalRange: '>60' },
          { id: 'test-3', group: 'Urine Analysis', name: 'Urine for AC Ratio (mg/gm)', result: '500', unit: 'mg/gm', normalRange: '<30' }
      ]},
      { id: 'inv-1-2', date: subDays(today, 30).toISOString(), tests: [
          { id: 'test-4', group: 'Biochemistry', name: 'Serum Creatinine', result: '1.4', unit: 'mg/dL', normalRange: '0.6-1.2' },
          { id: 'test-5', group: 'Biochemistry', name: 'eGFR', result: '58', unit: 'mL/min/1.73m²', normalRange: '>60' },
          { id: 'test-6', group: 'Urine Analysis', name: 'Urine for AC Ratio (mg/gm)', result: '450', unit: 'mg/gm', normalRange: '<30' }
      ]}
    ]
  },
  {
    id: 'patient-2',
    nephroId: '1002/0824',
    name: 'Isha Singh',
    dob: '1992-11-22',
    gender: 'Female',
    contact: '9988776655',
    email: 'isha.singh@example.com',
    address: { street: '45 Park Avenue', city: 'Delhi', state: 'Delhi', pincode: '110001' },
    guardian: { name: 'Rohan Singh', relation: 'Spouse', contact: '9988776654' },
    registrationDate: subDays(today, 120).toISOString(),
    createdAt: subDays(today, 120).toISOString(),
    patientStatus: 'OPD',
    isTracked: false,
    residenceType: 'Urban',
    nextAppointmentDate: addDays(today, 5).toISOString(),
    clinicalProfile: {
      primaryDiagnosis: 'IgA Nephropathy (IgAN)',
      tags: ['Glomerulonephritis', 'IgAN'],
      nutritionalStatus: 'Well-nourished',
      disability: 'None',
      subspecialityFollowUp: 'NIL',
      smokingStatus: 'No',
      alcoholConsumption: 'No',
      vaccinations: [],
      pomr: 'Recurrent hematuria. Biopsy-proven IgA Nephropathy.',
      aabhaNumber: 'ABHA-222',
      bloodGroup: 'B+',
      drugAllergies: 'None',
      whatsappNumber: '9988776655',
      hasDiabetes: false,
      onAntiHypertensiveMedication: true,
      onLipidLoweringMedication: false,
    },
    visits: [],
    investigationRecords: []
  },
  {
    id: 'patient-3',
    nephroId: '1003/0724',
    name: 'Vikram Reddy',
    dob: '1985-03-10',
    gender: 'Male',
    contact: '9123456789',
    email: 'vikram.reddy@example.com',
    address: { street: '78 Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033' },
    guardian: { name: 'Vikram Reddy', relation: 'Self', contact: '9123456789' },
    registrationDate: subDays(today, 45).toISOString(),
    createdAt: subDays(today, 45).toISOString(),
    patientStatus: 'IPD',
    isTracked: true,
    residenceType: 'Urban',
    nextAppointmentDate: null,
    clinicalProfile: {
      primaryDiagnosis: 'Acute Kidney Injury (AKI)',
      tags: ['AKI', 'Sepsis'],
      nutritionalStatus: 'Moderate malnutrition',
      disability: 'None',
      subspecialityFollowUp: 'Intensive Care',
      smokingStatus: 'No',
      alcoholConsumption: 'No',
      vaccinations: [],
      pomr: 'Admitted with sepsis leading to AKI. Requires RRT.',
      aabhaNumber: 'ABHA-333',
      bloodGroup: 'A-',
      drugAllergies: 'Penicillin',
      whatsappNumber: '9123456789',
      hasDiabetes: false,
      onAntiHypertensiveMedication: false,
      onLipidLoweringMedication: false,
    },
    visits: [
        {
            id: 'visit-3-1',
            date: subDays(today, 5).toISOString(),
            createdAt: subDays(today, 5).toISOString(),
            visitType: 'Admission',
            visitRemark: 'Admitted via ER with fever and hypotension.',
            groupName: 'Infection',
            patientId: 'patient-3'
        }
    ],
    investigationRecords: []
  },
  {
    id: 'patient-4',
    nephroId: '1004/0724',
    name: 'Anjali Menon',
    dob: '2000-08-01',
    gender: 'Female',
    contact: '9898989898',
    email: 'anjali.menon@example.com',
    address: { street: '22 Marine Drive', city: 'Kochi', state: 'Kerala', pincode: '682011' },
    guardian: { name: 'Suresh Menon', relation: 'F/O', contact: '9898989897' },
    registrationDate: subDays(today, 200).toISOString(),
    createdAt: subDays(today, 200).toISOString(),
    patientStatus: 'OPD',
    isTracked: true,
    residenceType: 'Semi-Urban',
    nextAppointmentDate: format(today, 'yyyy-MM-dd'),
    clinicalProfile: {
      primaryDiagnosis: 'Lupus Nephritis (LN)',
      tags: ['Lupus', 'Glomerulonephritis'],
      nutritionalStatus: 'Well-nourished',
      disability: 'None',
      subspecialityFollowUp: 'Rheumatology',
      smokingStatus: 'No',
      alcoholConsumption: 'No',
      vaccinations: [],
      pomr: 'SLE diagnosed 2 years ago. Now with active nephritis.',
      aabhaNumber: 'ABHA-444',
      bloodGroup: 'AB+',
      drugAllergies: 'None',
      whatsappNumber: '9898989898',
      hasDiabetes: false,
      onAntiHypertensiveMedication: true,
      onLipidLoweringMedication: false,
    },
    visits: [],
    investigationRecords: []
  }
];

export const MOCK_APPOINTMENTS: Appointment[] = [
    {
      id: 'appt-1',
      patientId: 'patient-1',
      patientName: 'Aarav Sharma',
      date: format(addDays(today, 14), 'yyyy-MM-dd'),
      createdAt: subDays(today, 5).toISOString(),
      time: '10:00',
      type: 'Follow-up',
      doctorName: 'Dr. Sachin',
      status: 'Scheduled',
    },
    {
      id: 'appt-2',
      patientId: 'patient-2',
      patientName: 'Isha Singh',
      date: format(addDays(today, 5), 'yyyy-MM-dd'),
      createdAt: subDays(today, 10).toISOString(),
      time: '11:30',
      type: 'Routine Checkup',
      doctorName: 'Dr. Atul',
      status: 'Scheduled',
    },
    {
      id: 'appt-3',
      patientId: 'patient-4',
      patientName: 'Anjali Menon',
      date: format(today, 'yyyy-MM-dd'),
      createdAt: subDays(today, 2).toISOString(),
      time: '09:30',
      type: 'GN Monitoring Visit',
      doctorName: 'Dr. Parikshit',
      status: 'Scheduled',
    },
    {
      id: 'appt-4',
      patientId: 'patient-1',
      patientName: 'Aarav Sharma',
      date: format(subDays(today, 30), 'yyyy-MM-dd'),
      createdAt: subDays(today, 40).toISOString(),
      time: '10:00',
      type: 'Follow-up',
      doctorName: 'Dr. Sachin',
      status: 'Completed',
    },
    {
      id: 'appt-5',
      patientId: 'patient-4',
      patientName: 'Anjali Menon',
      date: format(today, 'yyyy-MM-dd'),
      createdAt: subDays(today, 1).toISOString(),
      time: '14:00',
      type: 'Dialysis Session',
      doctorName: 'Dr. Sachin',
      status: 'Waiting',
    },
    {
      id: 'appt-6',
      patientId: 'patient-2',
      patientName: 'Isha Singh',
      date: format(today, 'yyyy-MM-dd'),
      createdAt: subDays(today, 1).toISOString(),
      time: '14:30',
      type: 'Consultation',
      doctorName: 'Dr. Sachin',
      status: 'Waiting',
    },
];

